name: RegulusDataReader
version: "0.0.1"
slug: regulus_data_reader
description: Run a Python script as a Home Assistant add-on
url: https://github.com/hajekmartin/regulusdatareader
arch:
    - armhf
    - armv7
    - amd64
    - aarch64
init: false
options:
  external_hostname: ''
  additional_hosts: []
schema:
  external_hostname: str?
  additional_hosts:
  - hostname: str
    service: str
    disableChunkedEncoding: bool?
  tunnel_name: str?
  tunnel_token: str?
  post_quantum: bool?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/brenner-tobias/cloudflared/{arch}