name: RegulusDataReader
version: "0.0.1"
slug: regulus_data_reader
description: Run a Python script as a Home Assistant add-on
url: https://github.com/hajekmartin/regulusdatareader
arch:
    - armhf
    - armv7
    - amd64
    - aarch64
init: false
config:
    - name: parameter1
        description: Description of parameter1
        required: true
        default: default_value1
    - name: parameter2
        description: Description of parameter2
        required: false
        default: default_value2

