name: RegulusDataReader
version: "0.0.4"
slug: regulus_data_reader
description: Run a Python script as a Home Assistant add-on
url: https://github.com/hajekmartin/regulusdatareader
arch:
    - armhf
    - armv7
    - amd64
    - aarch64
init: false
options:
  guid: ''
  get_regulus_objects: ''
  set_regulus_objects: ''
schema:
  guid: str
  get_regulus_objects: str
  set_regulus_objects: str
logger:
  default: info
system_log:
  max_entries: MAX_ENTRIES
